# Generated by Django 2.0.5 on 2018-06-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=16)),
                ('channel', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('page_number', models.IntegerField(default=0)),
                ('next_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=32)),
                ('campus', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Team'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Section'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Question'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Question'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Team'),
        ),
    ]
