# Generated by Django 2.0.6 on 2018-06-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20180601_2002_squashed_0005_fixture_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='next_section',
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checklist.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='page_number',
            field=models.IntegerField(default=-1),
        ),
    ]
