# Generated by Django 2.0.6 on 2018-07-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20180614_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subquestion', to='checklist.Question')),
            ],
        ),
    ]
