# Generated by Django 2.0.6 on 2018-07-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_subquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='question',
        ),
        migrations.AddField(
            model_name='fixture',
            name='subquestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='checklist.SubQuestion'),
            preserve_default=False,
        ),
    ]
