# Generated by Django 2.0.6 on 2018-07-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_subquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='checklist.Question'),
        ),
    ]
