# Generated by Django 2.0.6 on 2018-07-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_auto_20180725_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='subquestion',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='categoryId',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
