# Generated by Django 2.0.6 on 2018-07-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_auto_20180725_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestion',
            old_name='categoryId',
            new_name='titleId',
        ),
    ]
