# Generated by Django 2.0.6 on 2018-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_auto_20180726_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestion',
            old_name='titleId',
            new_name='categoryId',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='subquestionURL',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
