// URLS
export const TEAMS = "/api/teams/"
export const CHECKLIST = "/api/checklist/"

// Generic
export const SELECT_TEAM = "SELECT_TEAM"
export const FETCH_CHECKLIST = "FETCH_CHECKLIST"
export const FETCH_CHECKLIST_FULFILLED = FETCH_CHECKLIST + "_FULFILLED"
export const FETCH_TEAMS = "FETCH_TEAMS"
export const FETCH_TEAMS_FULFILLED = FETCH_TEAMS + "_FULFILLED"
//export const FETCH_TEAMS_REJECTED = FETCH_TEAMS + "_REJECTED"

// Index
export const SELECT_CAMPUS = "SELECT_CAMPUS"

// Navbar
export const SET_PERSON_NAME="SET_PERSON_NAME"

// Checklist
export const FETCH_SECTIONS = "FETCH_SECTIONS"
export const FETCH_SECTIONS_FULFILLED = FETCH_SECTIONS + "_FULFILLED"
export const FETCH_QUESTIONS = "FETCH_QUESTIONS"
export const FETCH_QUESTIONS_FULFILLED = FETCH_QUESTIONS + "_FULFILLED"

